apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        color: {{ .Values.color | quote }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: APP_VERSION
              value: {{ .Values.image.tag | quote }}
            - name: APP_COLOR
              value: {{ .Values.color | quote }}
            - name: NGINX_ENVSUBST_OUTPUT_DIR
              value: /usr/share/nginx/html
          volumeMounts:
            - name: html-template
              mountPath: /etc/nginx/templates
      volumes:
        - name: html-template
          configMap:
            name: {{ .Release.Name }}-html
