{
 "title": "K8s Showcase App",
 "tags": [ "kubecon-demo" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Application (namespace)",
    "query": "label_values(kube_namespace_status_phase{phase=\"Active\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "All Deployments (click Open to filter the dashboard below)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{namespace!~\"kube-system|kube-node-lease|kube-public|calico-system|tigera-operator|monitoring|rook-ceph|logging|opencost|ingress-nginx\"}"
    },
    {
     "expr": "kube_deployment_spec_replicas{namespace!~\"kube-system|kube-node-lease|kube-public|calico-system|tigera-operator|monitoring|rook-ceph|logging|opencost|ingress-nginx\"}"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pods running",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} == 1)",
     "legendFormat": "Pods running"
    }
   ]
  },
  {
   "title": "Pod count by Deployment",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count(label_replace(kube_pod_info{namespace=\"$namespace\"}, \"workload\", \"$1\", \"created_by_name\", \"(.*)-[a-z0-9]{5,10}$\")) by (workload)",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "CPU usage (cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(label_replace(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"\", container!=\"POD\"}[2m]), \"workload\", \"$1\", \"pod\", \"(.*)-[a-z0-9]+-[a-z0-9]{5}$\")) by (workload)",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Memory usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", container!=\"POD\"}, \"workload\", \"$1\", \"pod\", \"(.*)-[a-z0-9]+-[a-z0-9]{5}$\")) by (workload) / 1024 / 1024",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Pod logs (live)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{kubernetes_namespace_name=\"$namespace\"}"
    }
   ]
  }
 ]
}